### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by LinTsaiI**
林采儀
I finished the Part2 challenges, please check the link. Thank you.
http://174.129.52.161:3000/

### CODE REVIEW

**Comment by cwpeng** [comment]
If I search 館, there should be only 2 pages. But your code will load up to 4 pages of all attractions.

Fix it and leave comment for me to review again.

**Comment by LinTsaiI** [comment]
I fixed the loading extra pages problem. Please review again, thank you!

**Comment by LinTsaiI** [comment]
I fixed the loading extra pages problem. Please review the following link again, thank you!
http://174.129.52.161:3000/

**Review by cwpeng — APPROVED** [review]
OK. Done.

Suggestion: you can do it better if you add a global variable to track API loading status. Control your page can request API only once at the same time. Contact me if you cannot get my point.

**Pull request merged**
